=== vasilyrud/bgrapher/src/schema/bgraph.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "bgraph",
  "description": "A JSON representation of a bgraph.",
  "type": "object",
  "definitions": {
    "id": {
      "type": "integer",
      "minimum": 0
    },
    "coord": {
      "type": "integer",
      "minimum": 0
    },
    "color": {
      "type": "integer",
      "minimum": 0,
      "maximum": 16777215
    },
    "block": {
      "type": "object",
      "description": "Block in the bgraph.",
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "x": {
          "$ref": "#/definitions/coord"
        },
        "y": {
          "$ref": "#/definitions/coord"
        },
        "width": {
          "type": "integer",
          "minimum": 1
        },
        "height": {
          "type": "integer",
          "minimum": 1
        },
        "depth": {
          "type": "integer",
          "minimum": 0
        },
        "color": {
          "$ref": "#/definitions/color"
        },
        "label": {
          "type": "string"
        },
        "edgeEnds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/id"
          }
        }
      },
      "required": [
        "id",
        "x",
        "y",
        "width",
        "height",
        "depth",
        "color",
        "edgeEnds"
      ]
    },
    "edgeEnd": {
      "type": "object",
      "description": "End of an edge in the bgraph.",
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "x": {
          "$ref": "#/definitions/coord"
        },
        "y": {
          "$ref": "#/definitions/coord"
        },
        "color": {
          "$ref": "#/definitions/color"
        },
        "direction": {
          "type": "integer",
          "minimum": 1,
          "maximum": 4
        },
        "isSource": {
          "type": "boolean"
        },
        "label": {
          "type": "string"
        },
        "block": {
          "anyOf": [
            { "$ref": "#/definitions/id" },
            { "type": "null" }
          ]
        },
        "edgeEnds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/id"
          }
        }
      },
      "required": [
        "id",
        "x",
        "y",
        "color",
        "direction",
        "isSource",
        "block",
        "edgeEnds"
      ]
    }
  },
  "properties": {
    "width": {
      "type": "integer",
      "minimum": 0
    },
    "height": {
      "type": "integer",
      "minimum": 0
    },
    "bgColor": {
      "$ref": "#/definitions/color"
    },
    "highlightBgColor": {
      "$ref": "#/definitions/color"
    },
    "highlightFgColor": {
      "$ref": "#/definitions/color"
    },
    "blocks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/block"
      }
    },
    "edgeEnds": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/edgeEnd"
      }
    }
  },
  "required": [
    "width",
    "height",
    "blocks",
    "edgeEnds"
  ]
}

=== vasilyrud/bgrapher/test/bgraphs/edges.json
{
  "width":  5,
  "height": 5,
  "bgColor": 16777215,
  "highlightBgColor": 16777215,
  "highlightFgColor": 0,
  "blocks": [
    {
      "id": 0,
      "x": 0, "y": 0,
      "width": 2, "height": 1,
      "depth": 0, "color": 13421772,
      "edgeEnds": [
        0,
        1
      ]
    },
    {
      "id": 1,
      "x": 0, "y": 4,
      "width": 2, "height": 1,
      "depth": 0, "color": 13421772,
      "edgeEnds": [
        2,
        3
      ]
    },
    {
      "id": 2,
      "x": 3, "y": 4,
      "width": 1, "height": 1,
      "depth": 0, "color": 13421772,
      "edgeEnds": [
        4
      ]
    },
    {
      "id": 3,
      "x": 3, "y": 0,
      "width": 1, "height": 1,
      "depth": 0, "color": 13421772,
      "edgeEnds": [
      ]
    }
  ],
  "edgeEnds": [
    {
      "id": 0,
      "x": 0, "y": 1,
      "color": 0,
      "direction": 3,
      "isSource": true,
      "block": 0,
      "edgeEnds": [
        2,
        3,
        4
      ]
    },
    {
      "id": 1,
      "x": 1, "y": 1,
      "color": 0,
      "direction": 3,
      "isSource": true,
      "block": 0,
      "edgeEnds": [
        2,
        3
      ]
    },
    {
      "id": 2,
      "x": 0, "y": 3,
      "color": 0,
      "direction": 3,
      "isSource": false,
      "block": 1,
      "edgeEnds": [
        0,
        1
      ]
    },
    {
      "id": 3,
      "x": 1, "y": 3,
      "color": 0,
      "direction": 3,
      "isSource": false,
      "block": 1,
      "edgeEnds": [
        0,
        1
      ]
    },
    {
      "id": 4,
      "x": 3, "y": 3,
      "color": 0,
      "direction": 3,
      "isSource": false,
      "block": 2,
      "edgeEnds": [
        0
      ]
    },
    {
      "id": 5,
      "x": 4, "y": 1,
      "color": 0,
      "direction": 3,
      "isSource": true,
      "block": null,
      "edgeEnds": [
        6
      ]
    },
    {
      "id": 6,
      "x": 4, "y": 2,
      "color": 0,
      "direction": 3,
      "isSource": false,
      "block": null,
      "edgeEnds": [
        5
      ]
    }
  ]
}

=== vasilyrud/bgrapher/test/bgraphs/color.json
{
    "width":  4,
    "height": 4,
    "bgColor": 1,
    "highlightBgColor": 2,
    "highlightFgColor": 3,
    "blocks": [
        {
            "id": 0,
            "x": 0, "y": 0,
            "width": 2, "height": 1,
            "depth": 0, "color": 4,
            "edgeEnds": [
                0,
                100
            ]
        }
    ],
    "edgeEnds": [
        {
            "id": 0,
            "x": 0, "y": 1,
			"color": 5,
            "direction": 3,
            "isSource": true,
            "block": 0,
            "edgeEnds": [
                1
            ]
        },
        {
            "id": 100,
            "x": 1, "y": 1,
			"color": 6,
            "direction": 1,
            "isSource": false,
            "block": 0,
            "edgeEnds": [
                0
            ]
        }
    ]
}

=== vasilyrud/bgrapher/src/bgraphs/basic.json
{
    "width":  4,
    "height": 4,
    "blocks": [
        {
            "id": 0,
            "x": 0, "y": 0,
            "width": 1, "height": 1,
            "depth": 0, "color": 0,
            "edgeEnds": []
        },
        {
            "id": 100,
            "x": 2, "y": 0,
            "width": 1, "height": 1,
            "depth": 0, "color": 0,
            "edgeEnds": []
        },
        {
            "id": 2,
            "x": 0, "y": 2,
            "width": 1, "height": 1,
            "depth": 0, "color": 0,
            "edgeEnds": []
        },
        {
            "id": 123,
            "x": 2, "y": 2,
            "width": 1, "height": 1,
            "depth": 0, "color": 0,
            "edgeEnds": []
        }
    ],
    "edgeEnds": []
}

=== vasilyrud/bgrapher/test/bgraphs/samedepth.json
{
  "width":  4,
  "height": 4,
  "bgColor": 16777215,
  "highlightBgColor": 16777215,
  "highlightFgColor": 0,
  "blocks": [
    {
      "id": 0,
      "x": 0, "y": 0,
      "width": 2, "height": 2,
      "depth": 0, "color": 1,
      "edgeEnds": []
    },
    {
      "id": 100,
      "x": 1, "y": 1,
      "width": 2, "height": 2,
      "depth": 0, "color": 2,
      "edgeEnds": []
    }
  ],
  "edgeEnds": []
}

=== vasilyrud/bgrapher/test/bgraphs/basicedges.json
{
  "width":  4,
  "height": 4,
  "bgColor": 16777215,
  "highlightBgColor": 16777215,
  "highlightFgColor": 0,
  "blocks": [],
  "edgeEnds": [
    {
      "id": 0,
      "x": 0, "y": 0,
      "color": 0,
      "direction": 3,
      "isSource": true,
      "block": null,
      "edgeEnds": [
        100
      ]
    },
    {
      "id": 100,
      "x": 1, "y": 1,
      "color": 0,
      "direction": 1,
      "isSource": false,
      "block": null,
      "edgeEnds": [
        0
      ]
    }
  ]
}
